# Generated by Django 2.1.4 on 2019-01-09 14:46

from django.db import migrations, models
import djgeojson.fields

def create_geom(apps, schema_editor):
    AirKoreaStations = apps.get_model('dashboard', 'AirKoreaStations')
    for station in AirKoreaStations.objects.all():
        station.geom = {'type': 'Point', 'coordinates': [station.dmy, station.dmx]}
        station.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard',  '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airkoreastations',
            name='geom',
            field=djgeojson.fields.PointField(default=[37.4026616, 127.1010097]),
        ),
        migrations.RunPython(create_geom),
    ]
