# Generated by Django 2.1.4 on 2019-01-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190109_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, db_column='lat', decimal_places=10, max_digits=15, null=True)),
                ('lon', models.DecimalField(blank=True, db_column='lon', decimal_places=10, max_digits=15, null=True)),
                ('predValue', models.DecimalField(blank=True, db_column='predValue', decimal_places=10, max_digits=15, null=True)),
                ('type', models.TextField(blank=True, db_column='type', null=True)),
                ('dataTime', models.DateTimeField(blank=True, db_column='dataTime', null=True)),
            ],
        ),
    ]
